server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    
    error_page 500 502 503 504 /55x.html;
    location = /55x.html {
        root /usr/share/nginx/html;
    }
}
